### ISSUE TITLE
What's the difference between TrainDataset and TrainDatasetICCV?

### ISSUE THREAD

**Issue by sunjc0306** [simpleig/Geo-PIFu#11]
I am interested in your work. your code is rich, that includes rendering, DeepHuman and PIFu, which makes me beneficial for my research. As far as I know, PIFu needs other rendering results. However, there is no dataset in the same format as the original PIFu, and only same code is obtained. Whether PIFu or Geo-PIFu, they use TrainDatasetICCV class. What's the difference between TrainDataset and TrainDatasetICCV?

**Comment by LazerLikeFocus** [comment]
> 
> 
> I am interested in your work. your code is rich, that includes rendering, DeepHuman and PIFu, which makes me beneficial for my research. As far as I know, PIFu needs other rendering results. However, there is no dataset in the same format as the original PIFu, and only same code is obtained. Whether PIFu or Geo-PIFu, they use TrainDatasetICCV class. What's the difference between TrainDataset and TrainDatasetICCV?

The render_mesh.py doesn't make the files in specific folder,
As required in TrainDatasetICCV :
        self.RENDER = os.path.join(self.root, 'RENDER')
        self.MASK = os.path.join(self.root, 'MASK')
        self.PARAM = os.path.join(self.root, 'PARAM')
        self.UV_MASK = os.path.join(self.root, 'UV_MASK')
        self.UV_NORMAL = os.path.join(self.root, 'UV_NORMAL')
        self.UV_RENDER = os.path.join(self.root, 'UV_RENDER')
        self.UV_POS = os.path.join(self.root, 'UV_POS')
        self.OBJ = os.path.join(self.root, 'GEO', 'OBJ')

Can anyone tell me how these above files are generated and used in TrainDatasetICCV ?
