### ISSUE TITLE
opendr_requirements.yml file is outdated.

### ISSUE THREAD

**Issue by LazerLikeFocus** [simpleig/Geo-PIFu#18]
I have tried every method to setup env from the provided opendr_requirements.yml file.
All methods are from anaconda prompt (base):
1. Tried normal install from : conda env create --file opendr_requirements.yml => failed with a lot of conflict errors
2. To solve above i tried : [this](https://stackoverflow.com/questions/49154899/resolvepackagenotfound-create-env-using-conda-and-yml-file-on-macos) . Eventually editing the original yml file I moved the conflicting dependencies to pip. => fewer conflicting errors
3. To solve the above issue, I saw this [issue ](https://github.com/conda/conda/issues/6073#issuecomment-356981567) which told the problems caused by build numbers. And meanwhile I browsed PIFu's github repo and found there [yml ](https://github.com/shunsukesaito/PIFu/blob/master/environment.yml)file. It had no version numbers on there dependencies. So I tried it & removed build numbers from the dependencies in the opendr_requirements.yml
 => No luck as there were still conflicts (which told me the conflicts aren't due to build numbers and  are due to some internal python package conflicts)
4. So I opened the given create_opendrEnv.sh file and manually entered all the code line by line.
Some of the packages aren't available for python 2.7. 
Here is the create_opendrEnv.sh file. I have edited it to show which part of the code ran and what errors others produced. 
~code lines marked with * aren't working.
Check this : [create_opendrEnv - Copy.txt](https://github.com/simpleig/Geo-PIFu/files/6315420/create_opendrEnv.-.Copy.txt)
Packages that are not supported for python 2.7 give this error : 
(ERROR: Could not find a version that satisfies the requirement __required_python_package_ (from versions: none)
ERROR: No matching distribution found for __required_python_package_ )
---

I know you are busy but my dream is depended on this project.
Need to finish it somehow.
So Please respond.

**Comment by direcf** [comment]
Hi, LazerLikeFocus. I was on the same page like you. I also got trouble setting the conda environment(like opendrEnv), but now I succeed step3. Human Mesh Rendering and Voxelization step.

I used .sh file for setting environment, but there were many conflicts.
I mainly fixed two libraries which are opendr and opencv.

**opencv reinstall method**

$ sudo apt install libosmesa6-dev

$ sudo apt-get install build-essential

$ sudo apt-get install libgl1-mesa-dev

$ sudo apt-get install libglu1-mesa-dev

$ sudo apt-get install freeglut3-dev

$ pip install opendr

**opencv reinstall method**

$ conda install opencv=3.4.1=py27h6fd60c2_2

I am not sure this procedure working on you, but just try it!
Good luck! If you have any questions, please comment again.
