### ISSUE TITLE
Can't replicate conda environment

### ISSUE THREAD

**Issue by pabloinigoblasco** [simpleig/Geo-PIFu#9]
The instructions describe how to configure the conda environment based on some unexisting file in the current master HEAD.
The geopifu_requirements.yml file does not exist.

> conda env create -f geopifu_requirements.yml
conda activate geopifu

Are these instructions obsolete?

**Comment by simpleig** [comment]
Thanks for your interest in our work!
Typo fixed:
`geopifu_requirements.yml ---> geopifu_environment.yml`

**Comment by jsaisagar** [comment]
While creating opener environment, I am getting - pyqt==4.11.4=py27_4
  - qt==4.8.7=2

error

**Comment by nicolasugrinovic** [comment]
I get several conflict errors when trying to create **opendr env**. Could you provide just a list of requirements and not the exact environment specification?

**Comment by nicolasugrinovic** [comment]
@jsaisagar were you able to create the env?
